"""
错误码定义
"""
from enum import Enum


class ErrorCode(str, Enum):
    """API错误码枚举"""
    
    # 通用错误 (1000-1999)
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    
    # 文件相关错误 (2000-2999)
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    
    # 特征提取错误 (3000-3999)
    FEATURE_EXTRACTION_FAILED = "FEATURE_EXTRACTION_FAILED"
    FEATURE_EXTRACTION_TIMEOUT = "FEATURE_EXTRACTION_TIMEOUT"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    
    # 模型训练错误 (4000-4999)
    MODEL_TRAINING_FAILED = "MODEL_TRAINING_FAILED"
    MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
    INSUFFICIENT_SAMPLES = "INSUFFICIENT_SAMPLES"
    INVALID_LABELS = "INVALID_LABELS"
    
    # 预测错误 (5000-5999)
    PREDICTION_FAILED = "PREDICTION_FAILED"
    INVALID_FEATURES = "INVALID_FEATURES"
    FEATURE_MISMATCH = "FEATURE_MISMATCH"
    
    # 任务相关错误 (6000-6999)
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    TASK_ALREADY_COMPLETED = "TASK_ALREADY_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    
    # 参数错误 (7000-7999)
    INVALID_PARAMETER = "INVALID_PARAMETER"
    MISSING_REQUIRED_PARAMETER = "MISSING_REQUIRED_PARAMETER"
    PARAMETER_OUT_OF_RANGE = "PARAMETER_OUT_OF_RANGE"


# 错误码到HTTP状态码的映射
ERROR_CODE_TO_STATUS = {
    ErrorCode.INTERNAL_SERVER_ERROR: 500,
    ErrorCode.INVALID_REQUEST: 400,
    ErrorCode.VALIDATION_ERROR: 422,
    ErrorCode.NOT_FOUND: 404,
    ErrorCode.FILE_NOT_FOUND: 404,
    ErrorCode.FILE_UPLOAD_FAILED: 500,
    ErrorCode.FILE_TYPE_NOT_SUPPORTED: 400,
    ErrorCode.FILE_TOO_LARGE: 413,
    ErrorCode.FEATURE_EXTRACTION_FAILED: 500,
    ErrorCode.FEATURE_EXTRACTION_TIMEOUT: 504,
    ErrorCode.INSUFFICIENT_DATA: 400,
    ErrorCode.MODEL_TRAINING_FAILED: 500,
    ErrorCode.MODEL_NOT_FOUND: 404,
    ErrorCode.INSUFFICIENT_SAMPLES: 400,
    ErrorCode.INVALID_LABELS: 400,
    ErrorCode.PREDICTION_FAILED: 500,
    ErrorCode.INVALID_FEATURES: 400,
    ErrorCode.FEATURE_MISMATCH: 400,
    ErrorCode.TASK_NOT_FOUND: 404,
    ErrorCode.TASK_ALREADY_COMPLETED: 409,
    ErrorCode.TASK_FAILED: 500,
    ErrorCode.INVALID_PARAMETER: 400,
    ErrorCode.MISSING_REQUIRED_PARAMETER: 400,
    ErrorCode.PARAMETER_OUT_OF_RANGE: 400,
}

